[phases.setup]
nixPkgs = ["php82", "php82Packages.composer"]

[phases.install]
cmds = [
    "composer install --no-dev --optimize-autoloader --no-interaction",
    "chmod -R 775 storage bootstrap/cache"
]
